### ISSUE TITLE
The address from README is empty

### ISSUE THREAD

**Issue by utgarda** [jbaylina/ERC820#16]
Readme says `0x820Afdf355177C099f0251e96A8e8B2974307381` is the central registry address, but there's no contract deployed there: https://etherscan.io/address/0x820Afdf355177C099f0251e96A8e8B2974307381

on the other hand, there's a deployed contract at the address hardcoded in 
https://github.com/jbaylina/ERC820/blob/master/contracts/ERC820Client.sol
here it is:
https://etherscan.io/address/0x820c4597Fc3E4193282576750Ea4fcfe34DdF0a7
Is this the right one? It probably should go in the README

**Comment by 0xjac** [comment]
The correct address for ERC820 Registry is `0x820b586C8C28125366C998641B09DCbE7d4cBF06`.

However [ERC820] should **not be used** as it was superseded by [ERC1820].

Please use [ERC1820] instead, you can find the `erc1820` package [here](https://www.npmjs.com/package/erc1820) ([source](https://github.com/0xjac/ERC1820)).
The correct address for ERC1820 is `0x1820a4B7618BdE71Dce8cdc73aAB6C95905faD24` and it's in the README of the `erc1820` package 😉.

[ERC820]: https://eips.ethereum.org/EIPS/eip-820
[ERC1820]: https://eips.ethereum.org/EIPS/eip-1820
