### ISSUE TITLE
npm install fails unless mocha is installed globally

### ISSUE THREAD

**Issue by shane-t** [jbaylina/ERC820#24]
Because the prepack hook runs the test script, which calls `mocha --harmony`, unless a dependent package is installed in an environment where mocha is installed globally, this package will fail to install.

**Comment by 0xjac** [comment]
@shane-t I am not sure I understand. The `prepack` script does not run when installing the package only when packing or publishing it ([ref.](https://docs.npmjs.com/misc/scripts)). `mocha` is not required when installing the package as a dependency from npm.

If you are cloning the repository, make sure to run `npm install`.

More importantly the ERC820 registry provided in this package, is part of the [EIP820] standard which has been superseded by [EIP1820]. I suggest you work with the [EIP1820] standard. You can use the related [erc1820](https://www.npmjs.com/package/erc1820) package ([source](https://github.com/0xjac/ERC1820)).

The `erc1820` package is similar to this one (`erc820`), it also has a `prepack` script which calls `mocha` and `mocha` is a `devDependency` which won't be present but you should not need to call any script when installing `erc1820` as a dependency. The [CI is configured to call `prepack`](https://github.com/0xjac/ERC1820/blob/master/.circleci/config.yml#L122) and generate a package containing everything required for you to use `erc1820` straight away ([deployment run](https://circleci.com/gh/0xjac/ERC1820/92)). If you notice any bug, feel free to [open an issue on the ERC1820 repo](https://github.com/0xjac/ERC1820/issues/new).

[EIP820]: https://eips.ethereum.org/EIPS/eip-820
[EIP1820]: https://eips.ethereum.org/EIPS/eip-1820

**Comment by shane-t** [comment]
@0xjac thank you for your reply and explanation! Please feel free to close this (and the PR) for the above reasons - however I attach a log that shows this issue occurs if I do `npm install jbaylina/ERC820` just in case I'm not alone. 

I'll admit I'm not 100% clear about `npm install`ing things directly from source control, and whether it somehow executes `prepack` under unusual conditions.

[2019-04-15T17_21_56_363Z-debug.log](https://github.com/jbaylina/ERC820/files/3081329/2019-04-15T17_21_56_363Z-debug.log)

I note the standard has been superseded though. Thank you!

**Comment by 0xjac** [comment]
@shane-t thanks, I understand what happens, the prepack hook is called when installing from git (which is what `npm install jbaylina/ERC820` is. I'll open a corresponding issue in [0xjac/ERC1820](/0xjac/ERC1820). In the mean time, you can get around that by installing from npm: `npm install erc820` or preferably `npm install erc1820`.
