### ISSUE TITLE
Why hardcode? 

### ISSUE THREAD

**Issue by rstormsf** [jbaylina/ERC820#4]
https://github.com/jbaylina/eip820/blob/master/contracts/EIP820Implementer.sol#L11
shouldn't we use constructor? 
```
    function EIP820Implementer(address _registry) public {
      EIP820Registry eip820Registry = EIP820Registry(_registry);
    }
```

**Comment by jbaylina** [comment]
The idea is that this address will be fixed. Even in different chains.  Passing the Address in the constructor may result in mistakes.
