### ISSUE TITLE
eip777 imports another file

### ISSUE THREAD

**Issue by sponnet** [jbaylina/ERC820#9]
the file `ReferenceToken.sol` in the package ipe777 imports `EIP820Implementer.sol` instead of the old name 'ERC820Implementer.sol` therefor the linking does not work.
The file should be renamed in this package to be able to compile eip777

**Comment by jacquesd** [comment]
@sponnet thanks, we are working on renaming and reorganizing things. We will release new version in the next few days which should be compatible with each other. We will also make sure that the dependencies have correct version requirements.

**Comment by 0xjac** [comment]
This was actually resolved when ERC777 moved from ERC820 to ERC1820. The ERC1820 &lrarr; ERC777 dependencies should now be solved.
